INSERT INTO medicamentos (nombre, concentracion, forma_farmaceutica, presentacion) VALUES
	('Halotano', '0.9999', 'LIQ INH', '250mL'),
	('Isoflurano', '99.9-100%', 'LIQ INH', '100mL'),
	('Ketamina (como clorhidrato)', '50mg/mL', 'INY', '10mL'),
	('Óxido nitroso', '99-100%', 'GAS', 'para inhalación'),
	('Oxígeno medicinal', '99-100%', 'GAS', 'para inhalación'),
	('Propofol', '0.01', 'INY', '20mL'),
	('Sevoflurano', '99.97-100%', 'LIQ INH', '250mL'),
	('Tiopental sódico', '1g', 'INY', ''),
	('Bupivacaína clorhidrato + preservante', '0.005', 'INY', '20mL'),
	('Bupivacaína clorhidrato sin preservante', '0.005', 'INY', '20mL'),
	('Bupivacaína clorhidrato + glucosa', '0.5% + 7.5-8.0%', 'INY', '4mL'),
	('Lidocaína clorhidrato + epinefrina', '2% + 1:80 000', 'INY', 'cárpula'),
	('Lidocaína clorhidrato sin epinefrina', '0.02', 'INY', 'cárpula'),
	('Lidocaína clorhidrato', '2–4%', 'GEL TOP/JAL TOP', ''),
	('Lidocaína clorhidrato sin preservante sin epinefrina', '0.02', 'INY', '20mL'),
	('Lidocaína clorhidrato + preservante sin epinefrina', '0.02', 'INY', '20mL'),
	('Lidocaína clorhidrato + preservante + epinefrina', '2% + 1:200 000', 'INY', '20mL'),
	('Lidocaína clorhidrato sin preservante + epinefrina', '2% + 1:200 000', 'INY', '20mL'),
	('Lidocaína clorhidrato sin preservante + glucosa', '5% + 7.5%', 'INY', '2mL'),
	('Lidocaína', '0.1', 'AER TOP', ''),
	('Etilefrina', '10mg/mL', 'INY', ''),
	('Atropina sulfato', '1mg/mL', 'INY', ''),
	('Diazepam', '5mg/mL', 'INY', '2mL'),
	('Diazepam', '5mg', 'TAB', ''),
	('Diazepam', '10mg', 'TAB', ''),
	('Fentanilo (como citrato)', '50mcg/mL (0.05mg/mL)', 'INY', '2mL y 10mL'),
	('Midazolam (como clorhidrato)', '1mg/mL', 'INY', '5mL'),
	('Midazolam (como clorhidrato)', '5mg/mL', 'INY', '10mL'),
	('Morfina clorhidrato', '10mg/mL', 'INY', '1mL'),
	('Ácido acetilsalicílico', '500mg', 'TAB', ''),
	('Diclofenaco sódico', '25mg/mL', 'INY', '3mL'),
	('Ibuprofeno', '100mg/5mL', 'LIQ ORAL', ''),
	('Ibuprofeno', '200mg', 'TAB', ''),
	('Ibuprofeno', '400mg', 'TAB', ''),
	('Metamizol sódico', '500mg/mL', 'INY', '2mL'),
	('Naproxeno (como base o sal sódica)', '250mg', 'TAB', ''),
	('Naproxeno (como base o sal sódica)', '500mg', 'TAB', ''),
	('Paracetamol', '100mg/mL', 'LIQ ORAL', 'gotas'),
	('Paracetamol', '120mg/5mL', 'LIQ ORAL', ''),
	('Paracetamol', '100-300mg', 'SUP', ''),
	('Paracetamol', '500mg', 'TAB', ''),
	('Buprenorfina', '35mcg/h', 'PARCHE TRANS', ''),
	('Codeína fosfato', '10-15mg/5mL', 'LIQ ORAL', ''),
	('Codeína fosfato', '30mg', 'TAB', ''),
	('Codeína fosfato', '30mg/mL', 'INY', ''),
	('Codeína fosfato', '60mg', 'TAB', ''),
	('Metadona (como clorhidrato)', '10mg', 'TAB', ''),
	('Morfina clorhidrato', '10mg/mL', 'INY', '1mL'),
	('Morfina clorhidrato', '20mg/mL', 'INY', '1mL'),
	('Morfina sulfato', '10mg/5mL', 'LIQ ORAL', ''),
	('Morfina sulfato', '10mg', 'TAB', ''),
	('Morfina sulfato', '30mg', 'TAB', ''),
	('Morfina sulfato', '30mg', 'TAB LIB MODIF', ''),
	('Oxicodona clorhidrato', '5mg', 'TAB', ''),
	('Oxicodona clorhidrato', '10mg', 'TAB LIB MODIF', ''),
	('Petidina clorhidrato', '50mg/mL', 'INY', '2mL'),
	('Tramadol clorhidrato', '100mg/mL', 'LIQ ORAL', 'gotas'),
	('Tramadol clorhidrato', '50mg/mL', 'INY', ''),
	('Tramadol clorhidrato', '50mg', 'TAB', ''),
	('Amitriptilina clorhidrato', '25mg', 'TAB', ''),
	('Dexametasona fosfato (como sal sódica)', '4mg/mL', 'INY', '1mL'),
	('Dexametasona (como base o dexametasona fosfato sódico)', '2mg/5mL', 'LIQ ORAL', ''),
	('Dexametasona', '4mg', 'TAB', ''),
	('Diazepam', '5mg/mL', 'INY', '2mL'),
	('Diazepam', '5mg', 'TAB', ''),
	('Diazepam', '10mg', 'TAB', ''),
	('Escopolamina butilbromuro', '20mg/mL', 'INY', ''),
	('Fluoxetina (como clorhidrato)', '20mg', 'TAB', ''),
	('Haloperidol', '5mg/mL', 'INY', '1mL'),
	('Haloperidol', '2mg/mL', 'LIQ ORAL', 'gotas'),
	('Haloperidol', '5mg', 'TAB', ''),
	('Lactulosa', '3.1-3.7g/5mL', 'LIQ ORAL', ''),
	('Metoclopramida clorhidrato', '5mg/mL', 'INY', '2mL'),
	('Metoclopramida clorhidrato', '5mg/5mL', 'LIQ ORAL', ''),
	('Metoclopramida clorhidrato', '10mg', 'TAB', ''),
	('Midazolam (como clorhidrato)', '1mg/mL', 'INY', '5mL'),
	('Midazolam (como clorhidrato)', '5mg/mL', 'INY', '10mL'),
	('Ondansetron (como clorhidrato)', '2mg/mL', 'INY', '4mL'),
	('Ondansetron (como clorhidrato)', '8mg', 'TAB', ''),
	('Clorfenamina maleato', '1mg/mL', 'LIQ ORAL', 'gotas'),
	('Clorfenamina maleato', '10mg/mL', 'INY', '1mL'),
	('Clorfenamina maleato', '2mg/5mL', 'LIQ ORAL', ''),
	('Clorfenamina maleato', '4mg', 'TAB', ''),
	('Dexametasona fosfato (como sal sódica)', '4mg/mL', 'INY', '1mL'),
	('Epinefrina (como clorhidrato o tartrato ácido)', '1mg/mL', 'INY', '1mL'),
	('Hidrocortisona (como succinato sódico)', '100mg', 'INY', ''),
	('Loratadina', '10mg', 'TAB', ''),
	('Loratadina', '5mg/5mL', 'LIQ ORAL', ''),
	('Metilprednisolona (como succinato sódico)', '500mg', 'INY', ''),
	('Prednisona', '50mg', 'TAB', ''),
	('Prednisona', '20mg', 'TAB', ''),
	('Prednisona', '5mg', 'TAB', ''),
	('Carbón activado', '', 'PLV', ''),
	('Ipecacuana', '0.14% (7mg/5mL) alcaloides totales', 'LIQ ORAL', ''),
	('Acetilcisteína', '200mg/mL', 'INY', '10mL'),
	('Acetilcisteína', '100mg/5mL', 'LIQ ORAL', ''),
	('Amilo nitrito', '', 'LIQ INH', ''),
	('Atropina sulfato', '1mg/mL', 'INY', ''),
	('Atropina sulfato', '500mcg/mL (0.5mg/mL)', 'INY', ''),
	('Azul de Prusia', '500mg', 'TAB', ''),
	('Calcio gluconato', '10% (equiv 8.4mg/mL Ca)', 'INY', '10mL'),
	('Calcioedetato sódico', '200mg/mL', 'INY', '5mL'),
	('Dantroleno sódico', '20mg', 'INY', ''),
	('Deferoxamina mesilato', '500mg', 'INY', ''),
	('Dimercaprol', '50mg/mL', 'INY', '2mL'),
	('Flumazenil', '100mcg/mL (0.1mg/mL)', 'INY', '5mL'),
	('Hidroxocobalamina', '1mg/mL', 'INY', '1mL'),
	('Metiltioninio cloruro', '10mg/mL', 'INY', '10mL'),
	('Naloxona clorhidrato', '400mcg/mL (0.4mg/mL)', 'INY', '1mL'),
	('Pralidoxima clorhidrato', '1g', 'INY', ''),
	('Penicilamina', '250mg', 'TAB', ''),
	('Sodio nitrito', '30mg/mL', 'INY', '10mL'),
	('Sodio tiosulfato', '250mg/mL', 'INY', '50mL'),
	('Succímero', '100mg', 'TAB', ''),
	('Carbamazepina', '100mg/5mL', 'LIQ ORAL', ''),
	('Carbamazepina', '100mg', 'TAB', ''),
	('Carbamazepina', '200mg', 'TAB', ''),
	('Clonazepam', '500mcg (0.5mg)', 'TAB', ''),
	('Clonazepam', '2mg', 'TAB', ''),
	('Clonazepam', '2.5mg/mL', 'LIQ ORAL', 'gotas'),
	('Diazepam', '5mg/mL', 'INY', '2mL'),
	('Levetiracetam', '500mg', 'TAB', ''),
	('Levetiracetam', '1000mg', 'TAB', ''),
	('Levetiracetam', '100mg/mL', 'LIQ ORAL', ''),
	('Lorazepam', '2mg/mL', 'INY', '1mL'),
	('Lorazepam', '4mg/mL', 'INY', '1mL'),
	('Etosuximida', '250mg', 'TAB', ''),
	('Etosuximida', '250mg/5mL', 'LIQ ORAL', ''),
	('Fenitoína sódica', '100mg', 'TAB', ''),
	('Fenitoína', '125mg/5mL', 'LIQ ORAL', ''),
	('Fenitoína sódica', '50mg/mL', 'INY', '5mL'),
	('Fenitoína sódica', '50mg/mL', 'INY', '2mL'),
	('Fenobarbital', '100mg', 'TAB', ''),
	('Fenobarbital (como base o sal sódica)', '100mg/mL', 'INY', '2mL'),
	('Fenobarbital', '15mg/5mL', 'LIQ ORAL', ''),
	('Gabapentina', '300mg', 'TAB', ''),
	('Lamotrigina', '50mg', 'TAB', ''),
	('Magnesio sulfato', '200mg/mL', 'INY', '10mL'),
	('Magnesio sulfato', '500mg/mL', 'INY', '10mL'),
	('Valproato sódico', '250mg/5mL', 'LIQ ORAL', ''),
	('Valproato sódico', '200mg/mL', 'LIQ ORAL', 'gotas'),
	('Valproato sódico', '500mg', 'TAB LIB MODIF', ''),
	('Ácido valproico (como valproato sódico)', '100mg/mL', 'INY', ''),
	('Albendazol', '100mg/5mL', 'LIQ ORAL', '20mL'),
	('Albendazol', '200mg', 'TAB', ''),
	('Albendazol', '400mg', 'TAB', ''),
	('Ivermectina', '3mg', 'TAB', ''),
	('Ivermectina', '6mg', 'TAB', ''),
	('Ivermectina', '6mg/mL', 'LIQ ORAL', 'gotas'),
	('Mebendazol', '100mg', 'TAB', ''),
	('Mebendazol', '100mg/5mL', 'LIQ ORAL', ''),
	('Mebendazol', '500mg', 'TAB', ''),
	('Prazicuantel', '150mg', 'TAB', ''),
	('Prazicuantel', '600mg', 'TAB', ''),
	('Prazicuantel', '600mg', 'TAB', ''),
	('Triclabendazol', '250mg', 'TAB', ''),
	('Amoxicilina', '125mg/5mL', 'LIQ ORAL', ''),
	('Amoxicilina', '250mg/5mL', 'LIQ ORAL', ''),
	('Amoxicilina', '500mg/5mL', 'LIQ ORAL', ''),
	('Amoxicilina', '250mg', 'TAB', ''),
	('Amoxicilina', '500mg', 'TAB', ''),
	('Amoxicilina + ácido clavulánico (como sal potásica)', '125mg + 31.25mg/5mL', 'LIQ ORAL', ''),
	('Amoxicilina + ácido clavulánico (como sal potásica)', '250mg + 62.5mg/5mL', 'LIQ ORAL', ''),
	('Amoxicilina + ácido clavulánico (como sal potásica)', '500mg + 125mg', 'TAB', ''),
	('Ampicilina (como sal sódica)', '500mg', 'INY', ''),
	('Ampicilina (como sal sódica)', '1g', 'INY', ''),
	('Bencilpenicilina sódica', 'equiv 1 000 000UI Bencilpenicilina', 'INY', ''),
	('Bencilpenicilina procaínica', 'equiv 1 000 000UI Bencilpenicilina', 'INY', ''),
	('Bencilpenicilina benzatina', 'equiv 1 200 000UI Bencilpenicilina', 'INY', ''),
	('Bencilpenicilina benzatina', 'equiv 2 400 000UI Bencilpenicilina', 'INY', ''),
	('Dicloxacilina (como sal sódica)', '250mg', 'TAB', ''),
	('Dicloxacilina (como sal sódica)', '250mg/5mL', 'LIQ ORAL', ''),
	('Dicloxacilina (como sal sódica)', '500mg', 'TAB', ''),
	('Fenoximetilpenicilina (como sal potásica)', '1 000 000UI', 'TAB', ''),
	('Fenoximetilpenicilina (como sal potásica)', '300 000UI/5mL', 'LIQ ORAL', ''),
	('Oxacilina', '1g', 'INY', ''),
	('Oxacilina', '500mg', 'INY', ''),
	('Ampicilina (como sal sódica) + sulbactam (como sal sódica)', '1g + 500mg', 'INY', ''),
	('Piperacilina (como sal sódica) + tazobactam (como sal sódica)', '4g + 500mg', 'INY', ''),
	('Cefalexina', '500mg', 'TAB', ''),
	('Cefalexina', '250mg/5mL', 'LIQ ORAL', ''),
	('Cefazolina (como sal sódica)', '1g', 'INY', ''),
	('Cefuroxima (como axetil)', '250mg/5mL', 'LIQ ORAL', ''),
	('Cefuroxima (como axetil)', '500mg', 'TAB', ''),
	('Cefotaxima (como sal sódica)', '500mg', 'INY', ''),
	('Ceftazidima', '1g', 'INY', ''),
	('Ceftriaxona (como sal sódica)', '1g', 'INY', ''),
	('Imipenem + cilastatina (como sal sódica)', '500mg + 500mg', 'INY', ''),
	('Meropenem', '500mg', 'INY', ''),
	('Azitromicina', '200mg/5mL', 'LIQ ORAL', ''),
	('Azitromicina', '500mg', 'TAB', ''),
	('Claritromicina', '250mg/5mL', 'LIQ ORAL', ''),
	('Claritromicina', '500mg', 'TAB', ''),
	('Clindamicina (como palmitato)', '75mg/5mL', 'LIQ ORAL', ''),
	('Clindamicina (como clorhidrato)', '300mg', 'TAB', ''),
	('Clindamicina (como fosfato)', '150mg/mL', 'INY', '4mL'),
	('Eritromicina (como estearato o etilsuccinato)', '200-250mg/5mL', 'LIQ ORAL', ''),
	('Eritromicina (como estearato o etilsuccinato)', '500mg', 'TAB', ''),
	('Eritromicina (como estearato o etilsuccinato)', '125mg/5mL', 'LIQ ORAL', ''),
	('Amikacina (como sulfato)', '250mg/mL', 'INY', '2mL'),
	('Amikacina (como sulfato)', '50mg/mL', 'INY', '2mL'),
	('Gentamicina (como sulfato)', '10mg/mL', 'INY', '2mL'),
	('Gentamicina (como sulfato)', '40mg/mL', 'INY', '2mL'),
	('Gentamicina (como sulfato)', '80mg/mL', 'INY', '2mL'),
	('Sulfametoxazol + trimetoprima', '200mg + 40mg/5mL', 'LIQ ORAL', ''),
	('Sulfametoxazol + trimetoprima', '400mg + 80mg', 'TAB', ''),
	('Sulfametoxazol + trimetoprima', '800mg + 160mg', 'TAB', ''),
	('Sulfametoxazol + trimetoprima', '80mg + 16mg/mL', 'INY', ''),
	('Ciprofloxacino', '250mg/5mL', 'LIQ ORAL', ''),
	('Ciprofloxacino (como lactato)', '2mg/mL', 'INY', '100mL'),
	('Ciprofloxacino (como clorhidrato)', '500mg', 'TAB', ''),
	('Doxiciclina (como clorhidrato o hiclato)', '100mg', 'TAB', ''),
	('Cloranfenicol', '250mg', 'TAB', ''),
	('Cloranfenicol', '500mg', 'TAB', ''),
	('Cloranfenicol (como palmitato)', '250mg/5mL', 'LIQ ORAL', ''),
	('Cloranfenicol (como succinato sódico)', '1g', 'INY', ''),
	('Colistina (como colistimetato sódico)', '100mg-150mg', 'INY', ''),
	('Fosfomicina (como trometamol)', '3g', 'LIQ ORAL', ''),
	('Furazolidona', '100mg', 'TAB', ''),
	('Furazolidona', '50mg/5mL', 'LIQ ORAL', ''),
	('Metronidazol (como benzoato)', '250mg/5mL', 'LIQ ORAL', ''),
	('Metronidazol', '5mg/mL', 'INY', '100mL'),
	('Metronidazol', '500mg', 'TAB', ''),
	('Nitrofurantoina', '100mg', 'TAB', ''),
	('Nitrofurantoina', '25mg/5mL', 'LIQ ORAL', ''),
	('Vancomicina (como clorhidrato)', '500mg', 'INY', ''),
	('Clofazimina', '100mg', 'TAB', ''),
	('Clofazimina', '50mg', 'TAB', ''),
	('Dapsona', '100mg', 'TAB', ''),
	('Dapsona', '50mg', 'TAB', ''),
	('Rifampicina', '150mg', 'TAB', ''),
	('Rifampicina', '300mg', 'TAB', ''),
	('Ácido p-aminosalicílico', '4g', 'GRAN LIB PRO', ''),
	('Capreomicina (como sulfato)', '1g', 'INY', ''),
	('Cicloserina', '250mg', 'TAB', ''),
	('Ciprofloxacino (como clorhidrato)', '500mg', 'TAB', ''),
	('Estreptomicina (como sulfato)', '1g', 'INY', ''),
	('Estreptomicina (como sulfato)', '5g', 'INY', ''),
	('Etambutol', '25mg/mL', 'LIQ ORAL', ''),
	('Etambutol clorhidrato', '400mg', 'TAB', ''),
	('Etambutol + isoniazida + pirazinamida + rifampicina', '275mg + 75mg + 400mg + 150mg', 'TAB', ''),
	('Etionamida', '250mg', 'TAB', ''),
	('Isoniazida', '50mg/5mL', 'LIQ ORAL', ''),
	('Isoniazida', '100mg', 'TAB', ''),
	('Isoniazida + rifampicina', '75mg + 150mg', 'TAB', ''),
	('Isoniazida + rifampicina', '150mg + 150mg', 'TAB', ''),
	('Kanamicina (como sulfato)', '1g', 'INY', ''),
	('Pirazinamida', '500mg', 'TAB', ''),
	('Pirazinamida', '30mg/mL', 'LIQ ORAL', ''),
	('Rifampicina', '100mg/5mL', 'LIQ ORAL', ''),
	('Rifampicina', '150mg', 'TAB', ''),
	('Rifampicina', '300mg', 'TAB', ''),
	('Rifabutina', '150mg', 'TAB', ''),
	('Moxifloxacino (como clorhidrato)', '400mg', 'TAB', ''),
	('Levofloxacino', '250mg', 'TAB', ''),
	('Levofloxacino', '500mg', 'TAB', ''),
	('Amfotericina B (como deoxicolato sódico)', '50mg', 'INY', ''),
	('Clotrimazol', '500mg', 'OVU/TAB VAG', ''),
	('Fluconazol', '2mg/mL', 'INY', ''),
	('Fluconazol', '50mg', 'TAB', ''),
	('Fluconazol', '150mg', 'TAB', ''),
	('Flucitosina', '500mg', 'TAB', ''),
	('Griseofulvina', '250mg', 'TAB', ''),
	('Itraconazol', '100mg', 'TAB', ''),
	('Nistatina', '100 000UI/mL', 'LIQ ORAL', 'gotas'),
	('Nistatina', '500 000UI', 'TAB', ''),
	('Aciclovir', '200mg', 'TAB', ''),
	('Aciclovir (como sal sódica)', '250mg', 'INY', ''),
	('Aciclovir', '400mg', 'TAB', ''),
	('Abacavir (como sulfato)', '300mg', 'TAB', ''),
	('Estavudina', '30mg', 'TAB', ''),
	('Estavudina', '5mg/5mL', 'LIQ ORAL', ''),
	('Lamivudina', '150mg', 'TAB', ''),
	('Lamivudina', '50mg/5mL', 'LIQ ORAL', ''),
	('Tenofovir disoproxilo fumarato', '300mg (equiv 245mg tenofovir disoproxilo)', 'TAB', ''),
	('Zidovudina', '100mg', 'TAB', ''),
	('Zidovudina', '300mg', 'TAB', ''),
	('Zidovudina', '50mg/5mL', 'LIQ ORAL', ''),
	('Zidovudina', '10mg/mL', 'INY', '20mL'),
	('Efavirenz', '200mg', 'TAB', ''),
	('Efavirenz', '600mg', 'TAB', ''),
	('Etravirina', '100mg', 'TAB', ''),
	('Etravirina', '200mg', 'TAB', ''),
	('Nevirapina', '200mg', 'TAB', ''),
	('Nevirapina', '50mg/5mL', 'LIQ ORAL', ''),
	('Atazanavir (como sulfato)', '300mg', 'TAB', ''),
	('Darunavir (como etanolato)', '300mg', 'TAB', ''),
	('Darunavir (como etanolato)', '600mg', 'TAB', ''),
	('Indinavir (como sulfato)', '400mg', 'TAB', ''),
	('Lopinavir + ritonavir', '200mg + 50mg', 'TAB', ''),
	('Lopinavir + ritonavir', '400mg + 100mg/5mL', 'LIQ ORAL', ''),
	('Nelfinavir (como mesilato)', '250mg', 'TAB', ''),
	('Nelfinavir (como mesilato)', '50mg/g', 'LIQ ORAL', ''),
	('Ritonavir', '100mg', 'TAB', ''),
	('Saquinavir (como mesilato)', '500mg', 'TAB', ''),
	('Raltegravir', '400mg', 'TAB', ''),
	('Combinaciones a dosis fijas', '', '', ''),
	('Efavirenz + emtricitabina + tenofovir disoproxilo fumarato', '600mg + 200mg + 300mg (equiv 245mg tenofovir disoproxilo)', 'TAB', ''),
	('Emtricitabina + tenofovir disoproxilo fumarato', '200mg + 300mg (equiv 245mg tenofovir disoproxilo)', 'TAB', ''),
	('Lamivudina + nevirapina + estavudina', '150mg + 200mg + 30mg', 'TAB', ''),
	('Lamivudina + zidovudina + nevirapina', '150mg + 300mg + 200mg', 'TAB', ''),
	('Lamivudina + zidovudina', '150mg + 300mg', 'TAB', ''),
	('Entecavir', '0.5mg', 'TAB', ''),
	('Ganciclovir (como sal sódica)', '500mg', 'INY', ''),
	('Valganciclovir', '450mg', 'TAB', ''),
	('Ribavirina', '200mg', 'TAB', ''),
	('Peginterferón alfa-2a', '180mcg', 'INY', ''),
	('Interferón alfa-2b', '3 000 000 - 10 000 000UI', 'INY', ''),
	('Diloxanida furoato', '500mg', 'TAB', ''),
	('Metronidazol (como benzoato)', '250mg/5mL', 'LIQ ORAL', ''),
	('Metronidazol', '500mg', 'TAB', ''),
	('Amfotericina B (como deoxicolato sódico)', '50mg', 'INY', ''),
	('Antimoniato meglumina', 'equiv 80-85mg antimonio pentavalente/mL', 'INY', ''),
	('Estibogluconato sódico', 'equiv 100mg antimonio pentavalente/mL', 'INY', ''),
	('Miltefosina', '10mg', 'TAB', ''),
	('Miltefosina', '50mg', 'TAB', ''),
	('Pentamidina isetionato', '200mg', 'INY', ''),
	('Artemetero', '80mg/mL', 'INY', ''),
	('Artesunato', '60mg', 'INY', ''),
	('Artesunato', '250mg', 'TAB', ''),
	('Artesunato', '50mg', 'TAB', ''),
	('Artesunato', '100mg', 'SUP', ''),
	('Artesunato + mefloquina (como clorhidrato)', '25mg + 50mg', 'TAB', ''),
	('Artesunato + mefloquina (como clorhidrato)', '100mg + 200mg', 'TAB', ''),
	('Cloroquina (como fosfato)', '150mg', 'TAB', ''),
	('Doxiciclina (como clorhidrato o hiclato)', '100mg', 'TAB', ''),
	('Mefloquina (como clorhidrato)', '250mg', 'TAB', ''),
	('Primaquina (como fosfato)', '15mg', 'TAB', ''),
	('Primaquina (como fosfato)', '5mg', 'TAB', ''),
	('Primaquina (como fosfato)', '7.5mg', 'TAB', ''),
	('Quinina sulfato', '300mg', 'TAB', ''),
	('Quinina diclorhidrato', '300mg/mL', 'INY', '2mL'),
	('Sulfadoxina + pirimetamina', '500mg + 25mg', 'TAB', ''),
	('Pirimetamina', '25mg', 'TAB', ''),
	('Sulfametoxazol + trimetoprima', '800mg + 160mg', 'TAB', ''),
	('Sulfametoxazol + trimetoprima', '80mg + 16mg/mL', 'INY', ''),
	('Benznidazol', '100mg', 'TAB', ''),
	('Nifurtimox', '120mg', 'TAB', ''),
	('Ácido acetilsalicílico', '500mg', 'TAB', ''),
	('Ibuprofeno', '200mg', 'TAB', ''),
	('Ibuprofeno', '400mg', 'TAB', ''),
	('Paracetamol', '500mg', 'TAB', ''),
	('Paracetamol', '120mg/5mL', 'LIQ ORAL', ''),
	('Amitriptilina clorhidrato', '25mg', 'TAB', ''),
	('Propranolol clorhidrato', '40mg', 'TAB', ''),
	('Propranolol clorhidrato', '10mg', 'TAB', ''),
	('Azatioprina', '50mg', 'TAB', ''),
	('Ciclosporina', '100mg/mL', 'LIQ ORAL', ''),
	('Ciclosporina', '25mg', 'TAB', ''),
	('Ciclosporina', '50mg', 'TAB', ''),
	('Ciclosporina', '50mg/mL', 'INY', '1mL'),
	('Micofenolato mofetilo', '250mg', 'TAB', ''),
	('Micofenolato mofetilo', '500mg', 'TAB', ''),
	('Tacrolimus', '1mg', 'TAB', ''),
	('Tacrolimus', '5mg/mL', 'INY', ''),
	('Tacrolimus', '5mg', 'TAB', ''),
	('Asparaginasa', '10 000UI', 'INY', ''),
	('Azacitidina', '100mg', 'INY', ''),
	('Bleomicina (como sulfato)', '15mg (15UI)', 'INY', ''),
	('Bortezomib', '3.5mg', 'INY', ''),
	('Busulfano', '2mg', 'TAB', ''),
	('Busulfano', '6mg/mL', 'INY', '10mL'),
	('Capecitabina', '500mg', 'TAB', ''),
	('Carboplatino', '150mg', 'INY', ''),
	('Carboplatino', '450mg', 'INY', ''),
	('Carmustina', '100mg', 'INY', ''),
	('Cetuximab', '5mg/mL', 'INY', '20mL'),
	('Ciclofosfamida', '1g', 'INY', ''),
	('Ciclofosfamida', '200mg', 'INY', ''),
	('Ciclofosfamida', '50mg', 'TAB', ''),
	('Cisplatino', '10mg', 'INY', ''),
	('Cisplatino', '50mg', 'INY', ''),
	('Citarabina', '500mg', 'INY', ''),
	('Citarabina sin preservantes', '100mg', 'INY', ''),
	('Clorambucilo', '2mg', 'TAB', ''),
	('Dacarbazina', '200mg', 'INY', ''),
	('Dactinomicina', '500mcg (0.5mg)', 'INY', ''),
	('Dasatinib', '50mg', 'TAB', ''),
	('Dasatinib', '70mg', 'TAB', ''),
	('Daunorubicina (como clorhidrato)', '20mg', 'INY', ''),
	('Dexrazoxano (como clorhidrato)', '500mg', 'INY', ''),
	('Docetaxel', '20mg', 'INY', ''),
	('Docetaxel', '80mg', 'INY', ''),
	('Doxorubicina clorhidrato', '10mg', 'INY', ''),
	('Doxorubicina clorhidrato', '50mg', 'INY', ''),
	('Epirubicina clorhidrato', '10mg', 'INY', ''),
	('Epirubicina clorhidrato', '50mg', 'INY', ''),
	('Erlotinib (como clorhidrato)', '150mg', 'TAB', ''),
	('Etopósido', '20mg/mL', 'INY', '5mL'),
	('Etopósido', '50mg', 'TAB', ''),
	('Filgrastim', '30 000 000UI', 'INY', ''),
	('Filgrastim', '48 000 000UI', 'INY', ''),
	('Fludarabina fosfato', '50mg', 'INY', ''),
	('Fluorouracilo', '50mg/mL', 'INY', '10mL'),
	('Fluorouracilo', '50mg/mL', 'INY', '5mL'),
	('Folinato cálcico', 'equiv 15mg ácido folínico', 'TAB', ''),
	('Folinato cálcico', 'equiv 50mg ácido folínico', 'INY', ''),
	('Gemcitabina (como clorhidrato)', '1g', 'INY', ''),
	('Gemcitabina (como clorhidrato)', '200mg', 'INY', ''),
	('Hidroxicarbamida', '500mg', 'TAB', ''),
	('Ifosfamida', '1g', 'INY', ''),
	('Imatinib (como mesilato)', '100mg', 'TAB', ''),
	('Imatinib (como mesilato)', '400mg', 'TAB', ''),
	('Irinotecan clorhidrato', '100mg/5mL', 'INY', '5mL'),
	('Melfalan', '2mg', 'TAB', ''),
	('Melfalan (como clorhidrato)', '50mg', 'INY', ''),
	('Mercaptopurina', '50mg', 'TAB', ''),
	('Mesna', '100mg/mL', 'INY', '4mL'),
	('Metotrexato (como base o sal sódica)', '2.5mg', 'TAB', ''),
	('Metotrexato (como sal sódica)', '500mg', 'INY', ''),
	('Metotrexato (como sal sódica) con preservante', '50mg', 'INY', ''),
	('Metotrexato (como sal sódica) sin preservante', '50mg', 'INY', ''),
	('Mitomicina', '2mg', 'INY', ''),
	('Mitomicina', '20mg', 'INY', ''),
	('Mitoxantrona (como diclorhidrato)', '20mg', 'INY', ''),
	('Oxaliplatino', '100mg', 'INY', ''),
	('Oxaliplatino', '50mg', 'INY', ''),
	('Paclitaxel', '100mg', 'INY', ''),
	('Paclitaxel', '300mg', 'INY', ''),
	('Paclitaxel', '30mg', 'INY', ''),
	('Procarbazina (como clorhidrato)', '50mg', 'TAB', ''),
	('Rituximab', '10mg/mL', 'INY', '10mL'),
	('Rituximab', '10mg/mL', 'INY', '50mL'),
	('Sunitinib (como malato)', '25mg', 'TAB', ''),
	('Talidomida', '100mg', 'TAB', ''),
	('Temozolomida', '250mg', 'TAB', ''),
	('Temozolomida', '100mg', 'TAB', ''),
	('Tioguanina', '40mg', 'TAB', ''),
	('Trastuzumab', '440mg', 'INY', ''),
	('Trastuzumab', '600mg', 'INY', ''),
	('Tretinoina', '10mg', 'TAB', ''),
	('Vinblastina sulfato', '10mg', 'INY', ''),
	('Vincristina sulfato', '1mg', 'INY', ''),
	('Vinorelbina (como tartrato o ditartrato)', '50mg', 'INY', ''),
	('Anastrozol', '1mg', 'TAB', ''),
	('Bicalutamida', '150mg', 'TAB', ''),
	('Bicalutamida', '50mg', 'TAB', ''),
	('Flutamida', '250mg', 'TAB', ''),
	('Ciproterona acetato', '50mg', 'TAB', ''),
	('Dexametasona fosfato (como sal sódica)', '4mg/mL', 'INY', '1mL'),
	('Dexametasona', '4mg', 'TAB', ''),
	('Dietilestilbestrol', '1mg', 'TAB', ''),
	('Leuprorelina acetato', '7.5mg', 'INY', ''),
	('Prednisona', '20mg', 'TAB', ''),
	('Prednisona', '50mg', 'TAB', ''),
	('Prednisona', '5mg', 'TAB', ''),
	('Tamoxifeno (como citrato)', '20mg', 'TAB', ''),
	('Triptorelina (como acetato o pamoato)', '3.75mg', 'INY', ''),
	('Biperideno clorhidrato', '2mg', 'TAB', ''),
	('Biperideno lactato', '5mg/mL', 'INY', '1mL'),
	('Levodopa + carbidopa', '250mg + 25mg', 'TAB', ''),
	('Pramipexol diclorhidrato', '250mcg (0.25mg)', 'TAB', ''),
	('Pramipexol diclorhidrato', '1mg', 'TAB', ''),
	('Ácido fólico', '500mcg (0.5mg)', 'TAB', ''),
	('Epoetina alfa', '2 000UI/mL', 'INY', '1mL'),
	('Epoetina alfa', '4 000UI/mL', 'INY', '1mL'),
	('Hidroxocobalamina', '1mg/mL', 'INY', '1mL'),
	('Hierro (como sacarato)', '20mg Fe/mL', 'INY', '5mL'),
	('Hierro (como sulfato)', '15mg Fe/5mL', 'LIQ ORAL', ''),
	('Hierro (como sulfato)', '60mg Fe', 'TAB', ''),
	('Hierro (como sulfato)', '25mg Fe/mL', 'LIQ ORAL', 'gotas'),
	('Hierro (como sulfato) + ácido fólico', '60mg Fe + 400mcg', 'TAB', ''),
	('Ácido tranexámico', '1g', 'INY', ''),
	('Ácido tranexámico', '250mg', 'TAB', ''),
	('Dalteparina sódica', '25 000UI/mL', 'INY', '0.2mL'),
	('Enoxaparina sódica', '100mg/mL', 'INY', '0.4mL'),
	('Enoxaparina sódica', '100mg/mL', 'INY', '0.6mL'),
	('Heparina sódica', '5 000UI/mL', 'INY', '5mL'),
	('Fitomenadiona', '10mg/mL', 'INY', '1mL'),
	('Protamina sulfato', '10mg/mL', 'INY', '5mL'),
	('Warfarina sódica', '1mg', 'TAB', ''),
	('Warfarina sódica', '5mg', 'TAB', ''),
	('Concentrado de factor VIII', '', 'INY', ''),
	('Concentrado de complejo factor IX (factor II, VII, IX, X)', '', 'INY', ''),
	('Gelatina', '3.5% - 4%', 'INY', ''),
	('Atenolol', '100mg', 'TAB', ''),
	('Atenolol', '50mg', 'TAB', ''),
	('Bisoprolol fumarato', '5mg', 'TAB', ''),
	('Diltiazem clorhidrato', '60mg', 'TAB', ''),
	('Isosorbida dinitrato', '10mg', 'TAB', ''),
	('Isosorbida dinitrato', '5mg', 'TAB SL', ''),
	('Isosorbida mononitrato', '20mg', 'TAB', ''),
	('Gliceroltrinitrato', '5mg/mL', 'INY', ''),
	('Verapamilo clorhidrato', '80mg', 'TAB', ''),
	('Adenosina', '3mg/mL', 'INY', '2mL'),
	('Amiodarona clorhidrato', '200mg', 'TAB', ''),
	('Amiodarona clorhidrato', '50mg/mL', 'INY', '3mL'),
	('Atenolol', '500mcg/mL (0.5mg/mL)', 'INY', ''),
	('Atenolol', '100mg', 'TAB', ''),
	('Atenolol', '50mg', 'TAB', ''),
	('Bisoprolol fumarato', '5mg', 'TAB', ''),
	('Digoxina', '250mcg (0.25mg)', 'TAB', ''),
	('Verapamilo clorhidrato', '2.5mg/mL', 'INY', '2mL'),
	('Verapamilo clorhidrato', '80mg', 'TAB', ''),
	('Lidocaína clorhidrato sin preservante sin epinefrina', '0.02', 'INY', '5mL'),
	('Propafenona clorhidrato', '150mg', 'TAB', ''),
	('Amlodipino (como besilato)', '10mg', 'TAB', ''),
	('Amlodipino (como besilato)', '5mg', 'TAB', ''),
	('Bisoprolol fumarato', '5mg', 'TAB', ''),
	('Nifedipino', '30mg', 'TAB LIB MODIF', ''),
	('Atenolol', '100mg', 'TAB', ''),
	('Atenolol', '50mg', 'TAB', ''),
	('Carvedilol', '25mg', 'TAB', ''),
	('Carvedilol', '6.25mg', 'TAB', ''),
	('Carvedilol', '12.5mg', 'TAB', ''),
	('Captopril', '25mg', 'TAB', ''),
	('Enalapril maleato', '10mg', 'TAB', ''),
	('Enalapril maleato', '20mg', 'TAB', ''),
	('Labetalol', '5mg/mL', 'INY', '4mL'),
	('Hidroclorotiazida', '25mg', 'TAB', ''),
	('Metildopa', '250mg', 'TAB', ''),
	('Nitroprusiato sódico', '50mg', 'INY', ''),
	('Losartán potásico', '50mg', 'TAB', ''),
	('Bisoprolol fumarato', '5mg', 'TAB', ''),
	('Digoxina', '250mcg (0.25mg)', 'TAB', ''),
	('Digoxina', '50mcg/mL (0.05mg/mL)', 'LIQ ORAL', 'gotas'),
	('Dobutamina (como clorhidrato)', '12.5mg/mL', 'INY', '20mL'),
	('Furosemida', '10mg/mL', 'INY', '2mL'),
	('Furosemida', '40mg', 'TAB', ''),
	('Hidroclorotiazida', '25mg', 'TAB', ''),
	('Lanatósido C', '200mcg/mL (0.2mg/mL)', 'INY', ''),
	('Dopamina clorhidrato', '40mg/mL', 'INY', '5mL'),
	('Epinefrina (como clorhidrato o tartrato ácido)', '1mg/mL', 'INY', '1mL'),
	('Norepinefrina (como tartrato ácido)', '1mg/mL', 'INY', '4mL'),
	('Carvedilol', '25mg', 'TAB', ''),
	('Carvedilol', '12.5mg', 'TAB', ''),
	('Carvedilol', '6.25mg', 'TAB', ''),
	('Ácido acetilsalicílico', '80-100mg', 'TAB', ''),
	('Clopidogrel (como bisulfato)', '75mg', 'TAB', ''),
	('Estreptoquinasa', '1 500 000UI', 'INY', ''),
	('Alteplasa', '50mg', 'INY', ''),
	('Atorvastatina (como sal cálcica)', '20mg', 'TAB', ''),
	('Atorvastatina (como sal cálcica)', '40mg', 'TAB', ''),
	('Simvastatina', '40mg', 'TAB', ''),
	('Simvastatina', '20mg', 'TAB', ''),
	('Gemfibrozilo', '600mg', 'TAB', ''),
	('Indometacina (como sal sódica)', '1mg', 'INY', ''),
	('Nimodipino', '200mcg/mL (0.2mg/mL)', 'INY', '50mL'),
	('Nimodipino', '30mg', 'TAB', ''),
	('Clotrimazol', '0.01', 'CRM TOP', ''),
	('Clotrimazol', '0.01', 'SOL TOP', ''),
	('Ácido fusídico', '0.02', 'CRM TOP', ''),
	('Mupirocina (como mupirocina cálcica)', '0.02', 'CRM TOP', ''),
	('Mupirocina', '0.02', 'UNG TOP', '15g'),
	('Nitrofural', '0.002', 'POM', '500g'),
	('Nitrofural', '0.002', 'POM', '35g'),
	('Sulfadiazina de plata', '0.01', 'CRM TOP', '50g'),
	('Sulfadiazina de plata', '0.01', 'CRM TOP', '400-500g'),
	('Betametasona (como dipropionato)', '0.0005', 'CRM TOP', ''),
	('Clobetasol propionato', '0.0005', 'CRM TOP', ''),
	('Hidrocortisona (como acetato)', '0.01', 'CRM TOP', ''),
	('Triamcinolona acetonido', '0.00025', 'LOC', ''),
	('Benzoilo peróxido', '4-5%', 'GEL TOP', ''),
	('Bencilo benzoato', '0.25', 'LOC', ''),
	('Permetrina', '0.01', 'LOC', ''),
	('Permetrina', '0.05', 'CRM TOP', ''),
	('Acitretina', '25mg', 'TAB', ''),
	('Isotretinoina', '20mg', 'TAB', ''),
	('Óxido de zinc', '10-40%', 'CRM TOP/POM/PAS', ''),
	('Nitrato de plata', '', 'BARRA/LAPIZ', ''),
	('Fluoresceína sódica', '0.1', 'INY', ''),
	('Ciclopentolato clorhidrato', '0.01', 'SOL OFT', 'colirio'),
	('Fenilefrina clorhidrato', '0.025', 'SOL OFT', ''),
	('Bario sulfato', '', 'LIQ ORAL', ''),
	('Bario sulfato', '', 'SUS REC', ''),
	('Iotalamato meglumina', '0.6', 'INY', '50mL'),
	('Iohexol', 'equiv 300mg iodo/mL', 'INY', '50mL'),
	('Iohexol', 'equiv 300mg iodo/mL', 'INY', '100mL'),
	('Iohexol', 'equiv 350mg iodo/mL', 'INY', '50mL'),
	('Iohexol', 'equiv 350mg iodo/mL', 'INY', '100mL'),
	('Iopamidol', 'equiv 300mg iodo/mL', 'INY', '50mL'),
	('Iopamidol', 'equiv 300mg iodo/mL', 'INY', '100mL'),
	('Iopamidol', 'equiv 370mg iodo/mL', 'INY', '50mL'),
	('Iopamidol', 'equiv 370mg iodo/mL', 'INY', '100mL'),
	('Gadopentetato meglumina', '469.01mg/mL', 'INY', '15mL'),
	('Medicamentos para ayuda al diagnóstico', '', '', ''),
	('Bisacodilo', '10mg', 'SUP', ''),
	('Bisacodilo', '5mg', 'TAB LIB MODIF', ''),
	('Macrogol 3350 + potasio cloruro + sodio cloruro + sodio bicarbonato con o sin sodio sulfato', '', 'PLV', ''),
	('Sodio fosfato monobásico + sodio fosfato dibásico', '16g + 6g/100mL', 'SOL REC', ''),
	('Simeticona', '80mg/mL o mas', 'LIQ ORAL', 'gotas'),
	('Alcohol etílico', '70°', 'SOL TOP', ''),
	('Clorhexidina gluconato', '0.04', 'SOL TOP', ''),
	('Peróxido de hidrógeno', '3% (10vols)', 'SOL TOP', ''),
	('Yodo-povidona', '7-10%', 'SOL TOP', 'espuma'),
	('Yodo-povidona', '7-10%', 'SOL TOP', ''),
	('Glutaral', '0.02', 'SOL', 'pH 7.5-8'),
	('Hipoclorito sódico', '0.1', 'SOL', ''),
	('Espironolactona', '100mg', 'TAB', ''),
	('Espironolactona', '25mg', 'TAB', ''),
	('Furosemida', '10mg/mL', 'INY', '2mL'),
	('Furosemida', '20mg/5mL', 'LIQ ORAL', ''),
	('Furosemida', '40mg', 'TAB', ''),
	('Hidroclorotiazida', '12.5mg', 'TAB', ''),
	('Hidroclorotiazida', '25mg', 'TAB', ''),
	('Manitol', '0.2', 'INY', ''),
	('Aluminio hidróxido + magnesio hidróxido', '400mg + 400mg/5mL', 'LIQ ORAL', ''),
	('Bismuto subsalicilato', '87.33mg/5mL', 'LIQ ORAL', ''),
	('Omeprazol', '20mg', 'TAB LIB MODIF', ''),
	('Omeprazol (como sal sódica)', '40mg', 'INY', ''),
	('Ranitidina (como clorhidrato)', '25mg/mL', 'INY', '2mL'),
	('Ranitidina (como clorhidrato)', '150mg', 'TAB', ''),
	('Ranitidina (como clorhidrato)', '300mg', 'TAB', ''),
	('Dimenhidrinato', '10mg/mL', 'INY', '5mL'),
	('Dimenhidrinato', '50mg', 'TAB', ''),
	('Metoclopramida clorhidrato', '5mg/mL', 'INY', '2mL'),
	('Metoclopramida clorhidrato', '5mg/5mL', 'LIQ ORAL', ''),
	('Metoclopramida clorhidrato', '10mg', 'TAB', ''),
	('Ondansetron (como clorhidrato)', '8mg', 'TAB', ''),
	('Ondansetron (como clorhidrato)', '2mg/mL', 'INY', '4mL'),
	('Sulfasalazina', '500mg', 'TAB', ''),
	('Mesalazina', '500mg', 'SUP', ''),
	('Atropina sulfato', '250mcg/mL (0.25mg/mL)', 'INY', ''),
	('Atropina sulfato', '500mcg/mL (0.5mg/mL)', 'INY', ''),
	('Escopolamina butilbromuro', '20mg/mL', 'INY', ''),
	('Escopolamina butilbromuro', '10mg', 'TAB', ''),
	('Glicerol', '', 'SUP', ''),
	('Lactulosa', '3.1-3.7g/5mL', 'LIQ ORAL', ''),
	('Sales de rehidratación oral', '20.5g/L', 'PLV', ''),
	('Ver 6.1.3 Composición', '', '', ''),
	('Zinc sulfato', 'equiv 10mg Zn/5mL', 'LIQ ORAL', ''),
	('Zinc sulfato', 'equiv 20mg Zn', 'TAB', ''),
	('Monoetanolamina oleato', '0.05', 'INY', ''),
	('Dexametasona', '500mcg (0.5mg)', 'TAB', ''),
	('Dexametasona', '4mg', 'TAB', ''),
	('Dexametasona fosfato (como sal sódica)', '2mg/mL', 'INY', '2mL'),
	('Dexametasona (como base o dexametasona fosfato sódico)', '2mg/5mL', 'LIQ ORAL', ''),
	('Fludrocortisona acetato', '100mcg (0.1mg)', 'TAB', ''),
	('Hidrocortisona', '20mg', 'TAB', ''),
	('Hidrocortisona (como succinato sódico)', '100mg', 'INY', ''),
	('Metilprednisolona (como succinato sódico)', '125mg', 'INY', ''),
	('Metilprednisolona (como succinato sódico)', '500mg', 'INY', ''),
	('Prednisona', '20mg', 'TAB', ''),
	('Prednisona', '50mg', 'TAB', ''),
	('Prednisona', '5mg', 'TAB', ''),
	('Prednisona', '5mg/5mL', 'LIQ ORAL', ''),
	('Triamcinolona acetonido', '10mg/mL', 'INY', '5mL'),
	('Triamcinolona acetonido', '40mg/mL', 'INY', '1mL'),
	('Betametasona (como fosfato sódico)', '4mg/mL', 'INY', ''),
	('Testosterona enantato', '250mg/mL (equiv 180mg de testosterona/mL)', 'INY', ''),
	('Etinilestradiol + levonorgestrel', '30mcg + 150mcg', 'TAB', '21tab + 7tab sustancia sin efecto terapéutico'),
	('Levonorgestrel', '750mcg', 'TAB', ''),
	('Estradiol cipionato + medroxiprogesterona acetato', '5mg + 25mg', 'INY', ''),
	('Medroxiprogesterona acetato', '150mg/mL', 'INY', '1mL'),
	('Noretisterona enantato', '200mg/mL', 'INY', '1mL'),
	('Etonogestrel', '68mg', 'IMPLANTE', ''),
	('Estradiol', '1mg', 'TAB', ''),
	('Estriol', '0.001', 'CRM VAG', '15g'),
	('Estrógenos conjugados naturales', '625mcg (0.625mg)', 'TAB', ''),
	('Estrógenos conjugados + medroxiprogesterona acetato', '625mcg (0.625mg) + 2.5mg', 'TAB', '30tab'),
	('Medroxiprogesterona acetato', '5mg', 'TAB', ''),
	('Glibenclamida', '5mg', 'TAB', ''),
	('Gliclazida', '30mg', 'TAB LIB MODIF', ''),
	('Gliclazida', '60mg', 'TAB LIB MODIF', ''),
	('Insulina humana (ADN recombinante)', '100UI/mL', 'INY', '10mL'),
	('Insulina isofana humana (NPH) (ADN recombinante)', '100UI/mL', 'INY', '10mL'),
	('Metformina clorhidrato', '850mg', 'TAB', ''),
	('Metformina clorhidrato', '500mg', 'TAB', ''),
	('Desmopresina acetato', '10mcg/dosis', 'SPR NAS', '5mL'),
	('Clomifeno citrato', '50mg', 'TAB', ''),
	('Medroxiprogesterona acetato', '5mg', 'TAB', ''),
	('Progesterona', '100mg', 'TAB', ''),
	('Levotiroxina sódica', '50mcg (0.05mg)', 'TAB', ''),
	('Levotiroxina sódica', '75mcg (0.075mg)', 'TAB', ''),
	('Levotiroxina sódica', '100mcg (0.1mg)', 'TAB', ''),
	('Tiamazol', '5mg', 'TAB', ''),
	('Tiamazol', '20mg', 'TAB', ''),
	('Bromocriptina (como mesilato)', '2.5mg', 'TAB', ''),
	('Cabergolina', '500mcg (0.5mg)', 'TAB', ''),
	('Danazol', '200mg', 'TAB', ''),
	('Leuprorelina acetato', '3.75mg', 'INY', ''),
	('Menotropina', '75UI', 'INY', ''),
	('Gonadotrofina coriónica', '5 000UI', 'INY', ''),
	('Ácido alendrónico (como alendronato sódico)', '70mg', 'TAB', ''),
	('Ácido zoledrónico', '4mg', 'INY', ''),
	('Pamidronato disódico', '90mg', 'INY', ''),
	('Derivado proteico purificado de tuberculina', '', 'INY', ''),
	('Suero antirrábico', '', 'INY', ''),
	('Suero antibotrópico', '', 'INY', ''),
	('Suero anticrotálico', '', 'INY', ''),
	('Suero antilachésico', '', 'INY', ''),
	('Suero antiloxoscélico', '', 'INY', ''),
	('Antitoxina tetánica', '', 'INY', ''),
	('Antitoxina diftérica', '', 'INY', ''),
	('Inmunoglobulina anti-D (Rh0)', '', 'INY', ''),
	('Inmunoglobulina contra el tétanos', '', 'INY', ''),
	('Inmunoglobulina contra la hepatitis B', '', 'INY', ''),
	('Inmunoglobulina contra la rabia', '', 'INY', ''),
	('Inmunoglobulina humana normal', '0.05', 'INY', ''),
	('Vacuna contra el tétanos[2]', '', 'INY', ''),
	('Vacuna contra el neumococo (pediátrico)', '', 'INY', ''),
	('Vacuna contra el neumococo (adulto)', '', 'INY', ''),
	('Vacuna contra la difteria (pediátrico)', '', 'INY', ''),
	('Vacuna contra la difteria (adulto)', '', 'INY', ''),
	('Vacuna contra el meningococo', '', 'INY', ''),
	('Vacuna contra el rotavirus', '', 'LIQ ORAL', ''),
	('Vacuna contra el sarampión', '', 'INY', ''),
	('Vacuna contra el Haemophilus influenzae tipo B (HIB)', '', 'INY', ''),
	('Vacuna contra la fiebre amarilla', '', 'INY', ''),
	('Vacuna contra la hepatitis A', '', 'INY', ''),
	('Vacuna contra la hepatitis B (HVB pediátrico)', '', 'INY', ''),
	('Vacuna contra la hepatitis B (HVB adulto)', '', 'INY', ''),
	('Vacuna contra el virus de la influenza HSUR (pediátrico)', '', 'INY', ''),
	('Vacuna contra el virus de la influenza HSUR (adulto)', '', 'INY', ''),
	('Vacuna contra la tos ferina', '', 'INY', ''),
	('Vacuna contra la poliomielitis (IPV)', '', 'INY', ''),
	('Vacuna contra la poliomielitis (OPV)', '', 'LIQ ORAL', ''),
	('Vacuna contra la rabia (preparado en cerebro ratón lactante)', '', 'INY', ''),
	('Vacuna contra la rabia inactivada (preparado en cultivo celular)', '', 'INY', ''),
	('Vacuna contra la rubeola', '', 'INY', ''),
	('Vacuna contra la tuberculosis (BCG)', '', 'INY', ''),
	('Vacuna contra las parotiditis', '', 'INY', ''),
	('Vacuna contra la varicela', '', 'INY', ''),
	('Vacuna contra el virus del papiloma humano', '', 'INY', ''),
	('Atracurio besilato', '10mg/mL', 'INY', ''),
	('Neostigmina bromuro', '15mg', 'TAB', ''),
	('Neostigmina metilsulfato', '500mcg/mL (0.5mg/mL)', 'INY', '1mL'),
	('Piridostigmina bromuro', '1mg/mL', 'INY', ''),
	('Piridostigmina bromuro', '60mg', 'TAB', ''),
	('Rocuronio bromuro', '10mg/mL', 'INY', '5mL'),
	('Suxametonio cloruro', '500mg', 'INY', ''),
	('Vecuronio bromuro', '4mg', 'INY', ''),
	('Baclofeno', '10mg', 'TAB', ''),
	('Orfenadrina citrato', '100mg', 'TAB LIB MODIF', ''),
	('Orfenadrina citrato', '30mg/mL', 'INY', '2mL'),
	('Aciclovir', '0.03', 'UNG OFT', ''),
	('Ciprofloxacino (como clorhidrato)', '0.003', 'SOL OFT', '5mL'),
	('Natamicina', '0.05', 'SUS OFT', ''),
	('Tetraciclina clorhidrato', '0.01', 'UNG OFT', ''),
	('Prednisolona acetato', '0.01', 'SUS OFT', '5mL'),
	('Diclofenaco sódico', '0.001', 'SOL OFT', '5mL'),
	('Proximetacaína clorhidrato', '0.005', 'SOL OFT', '15mL'),
	('Acetazolamida', '250mg', 'TAB', ''),
	('Latanoprost', '0.00005', 'SOL OFT', '2.5mL'),
	('Pilocarpina clorhidrato', '0.02', 'SOL OFT', '10-15mL'),
	('Timolol (como maleato)', '0.005', 'SOL OFT', '5mL'),
	('Dorzolamida', '0.02', 'SOL OFT', '15mL'),
	('Carbacol', '0.0001', 'SOL INTRAO', ''),
	('Atropina sulfato', '0.01', 'SOL OFT', '5mL'),
	('Tropicamida', '0.01', 'SOL OFT', '15mL'),
	('Bevacizumab', '25mg/mL', 'INY', ''),
	('Ketotifeno (como fumarato)', '0.00025', 'SOL OFT', ''),
	('Hipromelosa', '0.003', 'SOL OFT', ''),
	('Hipromelosa', '0.003', 'GEL OFT', ''),
	('Ergometrina maleato', '200mcg/mL (0.2mg/mL)', 'INY', '1mL'),
	('Misoprostol', '25mcg (0.025mg)', 'TAB VAG', ''),
	('Misoprostol', '200mcg', 'TAB', ''),
	('Oxitocina', '10UI/mL', 'INY', '1mL'),
	('Isoxsuprina clorhidrato', '10mg', 'TAB', ''),
	('Isoxsuprina clorhidrato', '5mg/mL', 'INY', '2mL'),
	('Nifedipino', '10mg', 'TAB', ''),
	('Salbutamol (como sulfato)', '4mg', 'TAB', ''),
	('Solución concentrada para hemodiálisis (ácida)', '', 'SOL DIA', ''),
	('Solución concentrada para hemodiálisis con bicarbonato', 'formula estándar con 35-39mEq/L de bicarbonato', 'SOL DIA', ''),
	('Solución para diálisis peritoneal automatizada', '1.5% de Glucosa', 'SOL DIA', ''),
	('Solución para diálisis peritoneal con sistema de desconexión con doble bolsa', '1.5% de Glucosa', 'SOL DIA', ''),
	('Solución para diálisis peritoneal automatizada', '2.5% de Glucosa', 'SOL DIA', ''),
	('Solución para diálisis peritoneal con sistema de desconexión con doble bolsa', '2.5% de Glucosa', 'SOL DIA', ''),
	('Solución para diálisis peritoneal automatizada', '4.25% de Glucosa', 'SOL DIA', ''),
	('Solución para diálisis peritoneal con sistema de desconexión con doble bolsa', '4.25% de Glucosa', 'SOL DIA', ''),
	('Calcio carbonato', '1.25g (equiv 500mg Ca)', 'TAB', ''),
	('Sevelamero clorhidrato o carbonato', '800mg', 'TAB', ''),
	('Clorpromazina clorhidrato', '100mg', 'TAB', ''),
	('Clorpromazina clorhidrato', '25mg/mL', 'INY', ''),
	('Clozapina', '100mg', 'TAB', ''),
	('Clozapina', '25mg', 'TAB', ''),
	('Flufenazina decanoato o enantato', '25mg/mL', 'INY', '1mL'),
	('Haloperidol', '5mg', 'TAB', ''),
	('Haloperidol', '10mg', 'TAB', ''),
	('Haloperidol', '2mg/mL', 'LIQ ORAL', 'gotas'),
	('Haloperidol', '5mg/mL', 'INY', '1mL'),
	('Haloperidol (como decanoato)', '50mg/mL', 'INY', '1mL'),
	('Periciazina', '40mg/mL (1mg/gota)', 'LIQ ORAL', 'gotas'),
	('Periciazina', '10mg', 'TAB', ''),
	('Risperidona', '2mg', 'TAB', ''),
	('Sulpirida', '200mg', 'TAB', ''),
	('Tioridazina clorhidrato', '100mg', 'TAB', ''),
	('Trifluoperazina (como clorhidrato)', '5mg', 'TAB', ''),
	('Amitriptilina clorhidrato', '25mg', 'TAB', ''),
	('Fluoxetina (como clorhidrato)', '20mg', 'TAB', ''),
	('Mirtazapina', '30mg', 'TAB', ''),
	('Sertralina (como clorhidrato)', '50mg', 'TAB', ''),
	('Carbamazepina', '200mg', 'TAB', ''),
	('Litio carbonato', '300mg', 'TAB', ''),
	('Valproato sódico', '500mg', 'TAB LIB MODIF', ''),
	('Alprazolam', '500mcg (0.5mg)', 'TAB', ''),
	('Clonazepam', '2mg', 'TAB', ''),
	('Clobazam', '10mg', 'TAB', ''),
	('Diazepam', '5mg/mL', 'INY', '2mL'),
	('Diazepam', '5mg', 'TAB', ''),
	('Diazepam', '10mg', 'TAB', ''),
	('Levomepromazina (como maleato)', '100mg', 'TAB', ''),
	('Levomepromazina (como maleato)', '25mg', 'TAB', ''),
	('Zolpidem tartrato', '10mg', 'TAB', ''),
	('Clomipramina clorhidrato', '25mg', 'TAB', ''),
	('Disulfiram', '500mg', 'TAB', ''),
	('Metilfenidato clorhidrato', '10mg', 'TAB', ''),
	('Metilfenidato clorhidrato', '20mg', 'TAB LIB MODIF', ''),
	('Aminofilina', '25mg/mL', 'INY', '10mL'),
	('Beclometasona dipropionato', '250mcg/dosis', 'AER INH', ''),
	('Beclometasona dipropionato', '50mcg/dosis', 'AER INH', ''),
	('Budesonida', '100mcg/dosis', 'AER INH', ''),
	('Budesonida', '200mcg/dosis', 'AER INH', ''),
	('Epinefrina (como clorhidrato o tartrato ácido)', '1mg/mL', 'INY', '1mL'),
	('Fluticasona propionato + salmeterol (como xinafoato)', '250mcg + 25mcg/dosis', 'AER INH', ''),
	('Fluticasona propionato + salmeterol (como xinafoato)', '125mcg + 25mcg/dosis', 'AER INH', '120dosis'),
	('Ipratropio bromuro', '20mcg/dosis', 'AER INH', '200dosis'),
	('Salbutamol (como sulfato)', '100mcg/dosis', 'AER INH', '200-300dosis'),
	('Salbutamol (como sulfato)', '5mg/mL', 'SOL NBZ', ''),
	('Teofilina', '125mg', 'TAB LIB MODIF', ''),
	('Teofilina', '250mg', 'TAB LIB MODIF', ''),
	('Dextrometorfano bromhidrato', '15mg/5mL', 'LIQ ORAL', ''),
	('Surfactante pulmonar', '', 'SOL INTRAT/SUS INTRAT', ''),
	('Sales de rehidratación oral', '20.5g/L', 'PLV', ''),
	('Ver 6.1.3 Composición', '', '', ''),
	('Glucosa en agua', '0.05', 'INY', '100mL'),
	('Glucosa en agua', '0.05', 'INY', '250mL'),
	('Glucosa en agua', '0.05', 'INY', '500mL'),
	('Glucosa en agua', '0.05', 'INY', '1L'),
	('Glucosa en agua', '0.1', 'INY', '1L'),
	('Glucosa en agua', '0.333', 'INY', '20mL'),
	('Glucosa en agua', '0.5', 'INY', '1L'),
	('Glucosa en agua + sodio cloruro', '5% + 0.9%', 'INY', '1L'),
	('Solución polielectrolítica', '', 'INY', '1L'),
	('Ver 6.1.3 Composición', '', '', ''),
	('Potasio cloruro', '0.2', 'INY', '10mL'),
	('Solución Ringer lactato', '', 'INY', '1L'),
	('Ver 6.1.3 Composición', '', '', ''),
	('Sodio bicarbonato', '0.084', 'INY', '20mL'),
	('Sodio cloruro', '0.009', 'INY', '100mL'),
	('Sodio cloruro', '0.009', 'INY', '1L'),
	('Sodio cloruro', '0.009', 'INY', '20mL'),
	('Sodio cloruro', '0.009', 'INY', '250mL'),
	('Sodio cloruro', '0.009', 'INY', '500mL'),
	('Sodio cloruro', '0.2', 'INY', '20mL'),
	('Agua para inyección', '', 'INY', '5mL'),
	('Agua para inyección', '', 'INY', '10mL'),
	('Agua para inyección', '', 'INY', '1L'),
	('Ácido ascórbico', '100mg', 'TAB', ''),
	('Ácido fólico', '500mcg (0.5mg)', 'TAB', ''),
	('Calcio carbonato', '1.25g (equiv 500mg Ca)', 'TAB', ''),
	('Calcio gluconato', '10% (equiv 8.4mg/mL Ca)', 'INY', '10mL'),
	('Calcitriol', '1mcg/mL', 'INY', ''),
	('Calcitriol', '0.25mcg', 'TAB', ''),
	('Ergocalciferol', '1.25mg (50 000UI)', 'TAB', ''),
	('Ergocalciferol', '250mcg/mL (10 000UI/mL)', 'LIQ ORAL', ''),
	('Hidroxocobalamina', '1mg/mL', 'INY', '1mL'),
	('Nicotinamida', '100mg', 'TAB', ''),
	('Piridoxina clorhidrato', '25mg', 'TAB', ''),
	('Piridoxina clorhidrato', '50mg', 'TAB', ''),
	('Retinol (como palmitato)', '50 000UI', 'TAB', ''),
	('Retinol (como palmitato)', '100 000UI', 'TAB', ''),
	('Retinol (como palmitato)', '200 000UI', 'TAB', ''),
	('Tiamina clorhidrato', '100mg', 'TAB', ''),
	('Tiamina clorhidrato', '100mg/mL', 'INY', ''),
	('Budesonida', '100mcg/dosis', 'SPR NAS', ''),
	('Ciprofloxacino (como clorhidrato)', '0.003', 'SOL OTI', ''),
	('Cafeína citrato', '20mg/mL (equiv 10mg cafeína/mL)', 'INY', ''),
	('Cafeína citrato', '20mg/mL (equiv 10mg cafeína/mL)', 'LIQ ORAL', ''),
	('Ibuprofeno', '5mg/mL', 'INY', ''),
	('Indometacina (como sal sódica)', '1mg', 'INY', ''),
	('Alopurinol', '100mg', 'TAB', ''),
	('Alopurinol', '300mg', 'TAB', ''),
	('Colchicina', '500mcg (0.5mg)', 'TAB', ''),
	('Cloroquina (como fosfato)', '150mg', 'TAB', ''),
	('Azatioprina', '50mg', 'TAB', ''),
	('Aurotiomalato sódico', '50mg/mL', 'INY', '1mL'),
	('Hidroxicloroquina sulfato', '400mg (equiv 310mg hidroxicloroquina)', 'TAB', ''),
	('Metotrexato (como base o sal sódica)', '2.5mg', 'TAB', ''),
	('Penicilamina', '250mg', 'TAB', ''),
	('Sulfasalazina', '500mg', 'TAB', ''),
	('Ácido acetilsalicílico', '500mg', 'TAB', ''),
	('Dimenhidrinato', '10mg/mL', 'INY', '5mL'),
	('Dimenhidrinato', '50mg', 'TAB', ''),
	('Oxibutinina clorhidrato', '5mg', 'TAB', ''),
	('Potasio citrato', '1080mg', 'TAB LIB MODIF', ''),
	('Tamsulosina clorhidrato', '400mcg (0.4mg)', 'TAB LIB MODIF', ''),
	('Finasterida', '5mg', 'TAB', '');